POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
  "email": "mrsrjn224@gmail.com",
  "password": "@newpassword123",
  "newPassword": "@newpassword123",
  "name": "Srijan",
  "code":677797
}
